# Change these first
owner: harleykin # Your GitHub organization or username, where this repository lives
repo: dotnetuptime # The name of this repository

sites:
  - name: NickiFaulk.com
    url: https://www.nickifaulk.com
    icon: https://www.nickifaulk.com/favicon.ico
  - name: NowWereCookin.org
    url: https://www.nowwerecookin.org
    icon: https://www.nowwerecookin.org/favicon.png
  - name: Borg Collection
    url: https://fanlistings.nickifaulk.com
    icon: https://fanlistings.nickifaulk.com/favicon.ico
  - name: WebRing Compendium
    url: https://webrings.nickifaulk.com
    icon: https://webrings.nickifaulk.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  baseUrl: /dotnetuptime
  name: "Nitallica's Upptime"
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://harleykin.github.io/dotnetuptime/
  #    - title: GitHub
  #      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "robots"
      content: "noindex"
  theme: night
#  css: "body {background:url(https://i.ibb.co/LtWhWgx/NGC1499-Akar-3296.jpg) no-repeat fixed; background-size:cover; text-color:#ffffff;} card, main article, section article, canvas {background-color:#142435;} nav {background:none; text-color:#ffffff; border:0 none; font-weight:bold;} nav ul li a, footer p {text-color:#ffffff;} article {border:1px solid #1B2B40;}"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

robotsText: "User-agent: * \n Disallow: /"
